spring:
  application:
    name: microservice-second
  zipkin:
    baseUrl: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: basic
